version: 1.0.0.{build}
before_build:
- cmd: nuget restore
build:
  project: NLog.xLogger.sln
  verbosity: minimal
test_script:
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\nlog-xlogger\NLog.xLogger.Tests\bin\Debug\NLog.xLogger.Tests.dll -noshadow -appveyor" -returntargetcode -filter:"+[NLog.xLogger*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\NLog.xLogger_coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "NLog.xLogger_coverage.xml"